// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnodZFYYyAFkNu0kUC9KeylsgEkSyErlA',
    appId: '1:509019948756:web:c2944a10f678b514845d41',
    messagingSenderId: '509019948756',
    projectId: 'moji-todo',
    authDomain: 'moji-todo.firebaseapp.com',
    storageBucket: 'moji-todo.firebasestorage.app',
    measurementId: 'G-XYNE00K5G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa59_tRROkxCnYJnk7uzy6zbQBG1POqfY',
    appId: '1:509019948756:android:b1ef2f04fa9f4d20845d41',
    messagingSenderId: '509019948756',
    projectId: 'moji-todo',
    storageBucket: 'moji-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlQMir0szAefl00UjjD12DmslkHpqaV4',
    appId: '1:509019948756:ios:2791eb606a2fbf5b845d41',
    messagingSenderId: '509019948756',
    projectId: 'moji-todo',
    storageBucket: 'moji-todo.firebasestorage.app',
    iosBundleId: 'com.example.mojiTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxlQMir0szAefl00UjjD12DmslkHpqaV4',
    appId: '1:509019948756:ios:2791eb606a2fbf5b845d41',
    messagingSenderId: '509019948756',
    projectId: 'moji-todo',
    storageBucket: 'moji-todo.firebasestorage.app',
    iosBundleId: 'com.example.mojiTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnodZFYYyAFkNu0kUC9KeylsgEkSyErlA',
    appId: '1:509019948756:web:c0cdd2b6a40af177845d41',
    messagingSenderId: '509019948756',
    projectId: 'moji-todo',
    authDomain: 'moji-todo.firebaseapp.com',
    storageBucket: 'moji-todo.firebasestorage.app',
    measurementId: 'G-1Q91C7TQM3',
  );
}
